- script/upgrades/MU01/deploy/MU01-05-Deploy-BreakerBox.sol
- script/upgrades/MU01/deploy/MU01-06-Deploy-MedianDeltaBreaker.sol
- script/upgrades/MU02/MU02-01-Deploy-MedianDeltaBreaker.sol
This adds the script for deploying the median delta breaker with default/empty configuration and transferring it to governance so that we can later re-configure it with the right parameters in the MU02 activation CGP.
-
Ran the deployment simulation locally
- Fixes https://github.com/mento-protocol/mento-deployment/issues/59
Yes, since the old constructor didn't change
-
> feat: add medianDeltaBreakear deployment script

- script/upgrades/MU03/MU03.sol
- Since the ValueDeltaBreaker hasn't changed in MU03 and the breaking logic is already set for USDC/USD there is no need for setting it again. We only need to configure the breaker for the new EUROC/EUR rate.
- The values on mainnet for the USDC/USD rate feed are equal to the once in the config. 
- I ran an isolated simulation on baklava with only the valueDeltaBreaker part + the checks  
- also we are going to run the whole script on alfajores where the state is more simular to mainnet 
- Fixes #109 
- the configuration already is configured with the same values
> fix: remove unnecessary Value Delta Breaker transactions

- script/upgrades/eXOF/eXOFChecks.verify.sol
Added a few checks which I noticed were missing for the initialization parameters of the token. Didn't bother to get them to throw upon mismatch as I was mainly interested to ensure that things like name, symbol, etc were correctly set.
- Ran the simulation on Alfajores without any assertion logs
```
Starting eXOF checks:
==  Rate feeds ==
EUROCXOF: 0xeD35e46b095197dA30DdFFA5B91d386886d5ce0d
EURXOF: 0x40dC8528167557353fdcD98548AB2139A670Dd0b
CELOXOF: 0xB0FA15e002516d0301884059c0aaC0F0C72b019D
== Verifying Token Transactions ==
🟢 Contract ownerships transferred to governance
🟢 StableTokenXOFProxy has the correct implementation address
🟢 Constitution params configured correctly
🟢 eXOF has been added to the reserve
🟢 eXOF has been added to the fee currency whitelist
== Verifying exchanges == …
```
> test: add eXOF initialization parameters check

- script/upgrades/MU04/MU04.sol
While simulating MU04 on Alfajores we ran into a revert which was caused due to calling `isCollateralAsset` on `ReserveProxy` that is still pointing to the legacy implementation. Our speculation is that the reason this worked on Baklava is that at some point we upgraded the implementation of the legacy reserve contract to the new one outside of MU04.
Simulation now works on Alfajores ✅
> fix: remove isCollateralAsset check in MU04

- script/upgrades/MU04/Config.sol
This PR adds the final changes to the MU04 config. It further increases the trading limits for the cEUR/EUROC pair.
- n/a
parameters come from @sissnad and @rcroessmann 
https://github.com/mento-protocol/mento-core/issues/310
- n/a
- n/a
> feat: increase cEUR/EUROC trading limits

- bin/get-secrets.sh
`yarn secrets:get` errored on my machine with a shell syntax error on the `sed` usage which slightly differs between linux and macOS environments
This PR adds a macOS-specific version of this command (if runtime env is macOS, else nothing changes)
On the `main` branch, running `yarn secrets:get` threw an error:
```
$ ./bin/get-secrets.sh ./bin/../.env sed: 1: "./bin/../.env": invalid command code . sed: 1: "./bin/../.env": invalid command code . sed: 1: "./bin/../.env": invalid command code . error Command failed with exit code 1.
```
Copilot had this to say on the matter which made sense and the syntax change works for me locally:
> Fix for get-secrets.sh: added macOS-compatible path for `sed` util usage

- script/upgrades/MUGOV/MUGOV.sol
- script/upgrades/MUGOV/MUGOVChecks.sol
- script/upgrades/MUGOV/interfaces.sol
updates MUGOV to reflect the latest changes to Airgrab and GovernanceFactory contract. 
-> using mento treasury instead of Celo community fund for unclaimed tokens.  
pulled the latest develop into lib/mento-core-2.3.0
- Fixes https://github.com/mento-protocol/mento-core/issues/401
> feat: update airdrop refund address to Mento Treasury

- script/upgrades/MUGOV/MUGOV.sol
- script/upgrades/MUGOV/MUGOVChecks.sol
- script/upgrades/dependencies.json
Adds missing Mento Labs multisig address 0x655133d8E90F8190ed5c1F0f3710F602800C0150 to the mainnet dependencies
Fetches the Celo community treasury address from registry
Fixes post deployment checks
adds missing TBD variable for the MentoLiquiditySupport to the mainnet dependencies
- Fixes #182
> feat: add mentolabs and celo treasury addresses

- bin/cgp-check.sh
- bin/cgp-execute.sh
- bin/cgp-pass.sh
- bin/cgp.sh
- bin/setup.sh
Updates bash scripts to work with both Celo and Mento governances at the same time by introducing a new flag "-g".
If the governance is "celo", everything should work as before
If the governance is "mento", util scripts under "/mento" subfolder should be used to perform operations on the Mento Governance
Removed some unused flags and updated some related comments in bash scripts
Tested by running MUGOV on Celo gov
Mento gov side can not be tested until the rest of the scripts are created
- Fixes [#476](https://github.com/mento-protocol/mento-general/issues/476)
Compatible
> feat: update bash scripts to work for both governances

- bin/cgp.sh
- script/interfaces/IERC20Lite.sol
- script/interfaces/IGovernanceFactory.sol
- script/interfaces/IGovernor.sol
- script/interfaces/IMentoUpgrade.sol
- script/upgrades/MUGOV/interfaces.sol
- script/utils/Arrays.sol
- script/utils/Config.sol
- script/utils/FixidityLib.sol
- script/utils/mento/Chain.sol
- script/utils/mento/Contracts.sol
- script/utils/mento/ExecuteProposal.sol
- script/utils/mento/GovernanceHelper.sol
- script/utils/mento/Script.sol
- script/utils/mento/SimulateUpgrade.sol
Implements the scripts to create and execute proposals on Mento Governance
- updates pragma of files used by two governances to a accept both solc versions
- adds bravo compatible interface to interact with the mento governance
Get a diff between scripts under `script/utils/mento` and `script/utils` and confirm if the changes correctly reflects the differences between celo and mento governances
By running MUGOV on Mento Governance. 
https://alfajores.celoscan.io/tx/0x5ca16d5ef582a6ce2133735db348372b1d796e99bef647818a499d294d53203a
GovernanceFactory: 0x9491cF9e591BD3dce3936431d8563529B5024faD
Note: Blockscout is not indexing new contracts at this moment. For instance the newly deployed airdrop contract is not indexed on blockscout but celoscan was able to pick it up: …
> feat: mento gov utils scripts

- bin/get-secrets.sh
Some minor updates to `npm run secrets:get` with more output. Also handling the case of non-existing `.env` file a bit better now by copying `.env.example` into `.env` before pulling the secret values.
> Improved UX for ./bin/get-secrets.sh with more output and error handling

- script/upgrades/MU08/MU08.sol
- script/upgrades/MU08/MU08Checks.sol
Adds transactions to transfer proxy admin and PUSO contract ownership to MU08 and also implements the related post checks
No
CGP simulation
- Fixes #221 #222
> feat: transfer proxy admin and PUSO ownership

- script/upgrades/cCOP/Config.sol
Chainlink often reports prices very close to the 5 minutes mark, we sometimes end up in a situation where the pool no longer has a valid median until the new price is relayed, essentially disabling trading against the pool. Because of this we are increasing the `referenceRateResetFrequency` parameter of the pool to `6 minutes` so that there's a bit more buffer when relaying the chainlink price. This parameter is used in the [oracleHasValidMedian function](https://github.com/mento-protocol/mento-core/blob/develop/contracts/swap/BiPoolManager.sol#L527) inside the biPoolManager. This goes together with what we already did during the oracle whitelist proposal where we also increased the [report expiry time](https://github.com/mento-protocol/mento-deployment/pull/228/files#diff-e297bcdf0b5c9eaa …
> fix: update cCOP pool reset frequency

- script/upgrades/MU08/MU08.md
- script/upgrades/MU08/MU08.sol
- script/upgrades/MU08/MU08Checks.sol
Removes Anchorage addresses and instead whitelist the Reserve Multisig(0x87647780180B8f55980C7D3fFeFe08a9B29e9aE1) as `otherReserveAddresses` for onchain Reserve contract
no
Simulated on alfajores
- Fixes #229
> feat: add partial reserve multisig as other reserve addresses

- remappings.txt
- script/interfaces/IGovernanceFactory.sol
- script/upgrades/MU09/MU09.md
- script/upgrades/MU09/MU09.sol
- script/upgrades/MU09/MU09Checks.sol
- script/upgrades/MU09/deploy/MU09-Deploy-LockingProxyAdmin.sol
- Adds script to deploy a proxy admin for the locking contract along with a governance script + checks
- None
- Executed deployment, cgp & checks on local fork
- Fixes #240
> feat: add script to deploy locking proxy admin

- script/upgrades/MU08/MU08.md
- script/upgrades/MU08/MU08.sol
- script/upgrades/MU08/MU08Checks.sol
This updates the amount of CELO that will be return in celo governance as part of MU08. We went with a rough number of ~80M CELO but the exact amount is `82,406,987`.
N/A
Simulation is green on Alfajores
> fix: MU08 CELO return amounts

- script/upgrades/MU08/MU08.md
- script/upgrades/MU08/MU08.sol
- script/upgrades/MU08/MU08Checks.sol
The previous CELO amount to be returned to the Celo community (`82_406_987`) didn't include the CELO that was sent to the Reserve via the Reserve bolstering mechanism, which was an additional 3.5M CELO. This updates the amount to 85.9M in total.
The additional CELO was taken from on-chain epoch rewards data, for a total sum of `3,534,512.340972869827370586` CELO.
N/A
Simulation green on Mainnet.
> fix: update MU08 CELO return amount

- script/upgrades/MU08/MU08.sol
cGHS is not yet initialized so we can't call `owner()` or `_getImplementation()` in it like we do for other tokens, since it causes a revert. This skips all such calls for cGHS
N/A
Simulated on a fork/mainnet
> fix: handle cGHS proxy special cases

- script/upgrades/OracleMigration/OracleMigration.sol
- script/upgrades/OracleMigration/OracleMigrationChecks.sol
- script/upgrades/OracleRemoval/OracleRemoval.sol
- script/upgrades/OracleRemoval/OracleRemovalChecks.sol
Unfortunately the full migration proposal exceeded the block gas limit (it seems to have consumed ~37M gas), so we decided to split it into two proposals:
1) Oracle removal proposal, where we exclusively remove all whitelisted addresses from SortedOracles. This is the most gas consuming part as it contains 128 transactions.
2) The actual migration proposal, in which we whitelist the new relayers, set the tokenExpiry and re-create the exchanges.
We will propose both of them roughly at the same time as Oracle Migration pt. 1 and pt.2 so that people can see them as a bundle and vote on them roughly together.
N/A
The simulations for the Oracle removal proposal
`yarn cgp -n celo -u OracleRemoval -g celo -s`
and the Oracle migration
`yarn cgp -n celo -u OracleMigration -g celo -s`
are both …
> fix: split oracle migration into 2 proposals

- script/upgrades/MU08/MU08.md
- script/upgrades/MU08/MU08.sol
- script/upgrades/MU08/MU08Checks.sol
This adds the sorted oracles proxy ownership transfer to MU08
Removed some no longer needed code around cGHS
Simulations are green. Note that the implementation of the sorted oracles contract is not owned by Celo Governance and therefore can't be transferred:
>   🟢 Proxy:[0xefB84935239dAcdecF7c5bA76d8dE40b077B7b33] ownership transferred to Mento Governance
🟢 Proxy:[0xefB84935239dAcdecF7c5bA76d8dE40b077B7b33] admin ownership transferred to Mento Governance
🟡 Warning Implementation:[0x93da60DCdDA3229246769CcE307076C181F41F72] ownership not transferred to Mento Governance 🟡
> feat: add sortedOracles transfer to MU08

- script/upgrades/MGP07/MGP07.md
- script/upgrades/MGP07/MGP07.sol
- script/upgrades/MGP07/MGP07Checks.sol
MGP to enable the transferability of the MENTO token.
N/A
Wrote checks for:
- checking that the state of the contract is "unpaused"
- simulating a token transfer from a token holder address
> feat: MGP-7: MENTO token transferability
